import { useState } from 'react';
import { ChevronRight, FolderTree, Plus } from 'lucide-react';
import type { QuestionTaxonomy, TaxonomyLevel } from '../types/question';

export function TaxonomyManager({ taxonomy, onCreate }: { taxonomy: QuestionTaxonomy; onCreate: (level: TaxonomyLevel, parentId: string, name: string) => Promise<void> }) {
  const [courseId, setCourseId] = useState(taxonomy.courses[0]?.id ?? ''); const [subjectId, setSubjectId] = useState(''); const [chapterId, setChapterId] = useState(''); const [lessonId, setLessonId] = useState(''); const [creating, setCreating] = useState<{ level: TaxonomyLevel; parentId: string } | null>(null); const [name, setName] = useState('');
  const columns = [
    { label: 'Subjects', level: 'subject' as const, parentId: courseId, items: taxonomy.subjects.filter((x) => x.courseId === courseId), selected: subjectId, select: (id: string) => { setSubjectId(id); setChapterId(''); setLessonId(''); } },
    { label: 'Chapters', level: 'chapter' as const, parentId: subjectId, items: taxonomy.chapters.filter((x) => x.subjectId === subjectId), selected: chapterId, select: (id: string) => { setChapterId(id); setLessonId(''); } },
    { label: 'Lessons', level: 'lesson' as const, parentId: chapterId, items: taxonomy.lessons.filter((x) => x.chapterId === chapterId), selected: lessonId, select: setLessonId },
    { label: 'Topics', level: 'topic' as const, parentId: lessonId, items: taxonomy.topics.filter((x) => x.lessonId === lessonId), selected: '', select: () => undefined },
  ];
  const create = async () => { if (!creating || !name.trim()) return; await onCreate(creating.level, creating.parentId, name); setCreating(null); setName(''); };
  return <section className="pf-taxonomy-manager"><header><div><small>ACADEMIC HIERARCHY</small><h2>Question taxonomy</h2><p>Create reusable subjects, chapters, lessons, and topics. Courses remain managed in Courses.</p></div><label className="pf-admin-field"><span>Course</span><select className="pf-admin-select" value={courseId} onChange={(event) => { setCourseId(event.target.value); setSubjectId(''); setChapterId(''); setLessonId(''); }}>{taxonomy.courses.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label></header><div className="pf-taxonomy-columns">{columns.map((column) => <section key={column.level}><header><strong>{column.label}</strong><button type="button" disabled={!column.parentId} onClick={() => setCreating({ level: column.level, parentId: column.parentId })} aria-label={`Add ${column.level}`}><Plus /></button></header>{column.parentId ? column.items.map((entry) => <button type="button" className={column.selected === entry.id ? 'is-active' : ''} key={entry.id} onClick={() => column.select(entry.id)}><span>{entry.name}</span>{column.level !== 'topic' ? <ChevronRight /> : null}</button>) : <div className="pf-taxonomy-empty"><FolderTree /><span>Select the previous level</span></div>}</section>)}</div>{creating ? <div className="pf-taxonomy-create"><label className="pf-admin-field"><span>New {creating.level}</span><input autoFocus className="pf-admin-input" value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void create(); }} /></label><button className="pf-admin-button pf-admin-button--quiet" type="button" onClick={() => setCreating(null)}>Cancel</button><button className="pf-admin-button" type="button" onClick={() => void create()}>Create</button></div> : null}</section>;
}
