import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Archive, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { useCourseStore } from '@/app/store/useCourseStore';
import type { AdminCourse, CourseStatus } from '@/features/admin/types/admin';
import type { CourseInput } from './courseRepository';
import { AdminDialog, AdminEmptyState, AdminPageHeader, AdminSkeleton, AdminStatusBadge, AdminToast, type AdminToastData } from '../AdminUi';
import './courses.css';

const blank = (): CourseInput => ({ name: '', code: '', description: '', status: 'ACTIVE' });
const tone = (status: CourseStatus) => status === 'ACTIVE' ? 'success' : status === 'INACTIVE' ? 'warning' : 'neutral';
const formatDate = (value: string) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value));

const CourseEditor = ({ course, onClose }: { course: AdminCourse | null; onClose: () => void }) => {
  const createCourse = useCourseStore((state) => state.createCourse); const updateCourse = useCourseStore((state) => state.updateCourse);
  const [form, setForm] = useState<CourseInput>(course ? { name: course.name, code: course.code, description: course.description, status: course.status } : blank());
  const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { course ? await updateCourse(course.id, form) : await createCourse(form); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Course could not be saved.'); } finally { setSaving(false); } };
  return <form className="pf-course-editor" onSubmit={submit}><div className="pf-course-editor__grid"><label className="pf-admin-field"><span>Course name</span><input className="pf-admin-input" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Chartered Accountancy" required /></label><label className="pf-admin-field"><span>Course code (Optional)</span><input className="pf-admin-input" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toLocaleUpperCase() })} placeholder="CA (Auto-generated if empty)" maxLength={16} /></label></div><label className="pf-admin-field"><span>Description</span><textarea className="pf-admin-textarea" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Professional accounting and finance education." /></label><label className="pf-admin-field"><span>Status</span><select className="pf-admin-select" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as CourseStatus })}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="ARCHIVED">Archived</option></select></label>{error ? <p className="pf-course-editor__error" role="alert">{error}</p> : null}<div className="pf-course-editor__actions"><button className="pf-admin-button pf-admin-button--quiet" type="button" onClick={onClose} disabled={saving}>Cancel</button><button className="pf-admin-button" disabled={saving}>{saving ? 'Saving…' : course ? 'Save changes' : 'Create course'}</button></div></form>;
};

export default function CoursesPage() {
  const initialize = useCourseStore((state) => state.initialize); const status = useCourseStore((state) => state.status); const error = useCourseStore((state) => state.error); const courses = useCourseStore((state) => state.courses); const remove = useCourseStore((state) => state.deleteCourse);
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<AdminCourse | null | undefined>(undefined); const [deleting, setDeleting] = useState<AdminCourse | null>(null); const [toast, setToast] = useState<AdminToastData | null>(null);
  useEffect(() => { void initialize(); }, [initialize]);
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase(); return term ? courses.filter((course) => [course.name, course.code, course.description].some((value) => value.toLocaleLowerCase().includes(term))) : courses; }, [courses, search]);
  const onDeleted = async () => { if (!deleting) return; try { await remove(deleting.id); setToast({ id: `deleted-${deleting.id}`, title: 'Course deleted', message: 'The course record was removed; existing related data remains intact.', tone: 'success' }); setDeleting(null); } catch (reason) { setToast({ id: 'course-delete-error', title: 'Course could not be deleted', message: reason instanceof Error ? reason.message : 'Please try again.', tone: 'error' }); } };
  return <motion.div className="pf-admin-page" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .24 }}>
    <AdminPageHeader title="Courses" description="The source of truth for course-specific students, orders, content, packages, and questions." actions={<button className="pf-admin-button" onClick={() => setEditing(null)}><Plus size={16} /> New course</button>} />
    <section className="pf-admin-table-card"><div className="pf-admin-table-card__header"><label className="pf-admin-search-field"><Search size={17} /><span className="pf-admin-sr-only">Search courses</span><input className="pf-admin-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search courses" /></label></div>{status === 'loading' ? <AdminSkeleton rows={6} variant="table" label="Loading courses" /> : null}{error ? <AdminEmptyState title="Courses could not load" description={error} /> : null}{status === 'ready' && filtered.length ? <div className="pf-admin-table-scroll"><table className="pf-admin-table"><thead><tr><th>Course</th><th>Code</th><th>Status</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{filtered.map((course) => <tr key={course.id}><td><strong>{course.name}</strong><small className="pf-course-table__description">{course.description || 'No description'}</small></td><td><code>{course.code}</code></td><td><AdminStatusBadge tone={tone(course.status)}>{course.status}</AdminStatusBadge></td><td>{formatDate(course.createdAt)}</td><td>{formatDate(course.updatedAt)}</td><td><span className="pf-course-actions"><button className="pf-admin-button pf-admin-button--secondary" onClick={() => setEditing(course)}><Pencil size={14} /> Edit</button><button className="pf-admin-icon-button" aria-label={`Delete ${course.name}`} onClick={() => setDeleting(course)}><Trash2 size={16} /></button></span></td></tr>)}</tbody></table></div> : null}{status === 'ready' && !filtered.length ? <AdminEmptyState icon={<Archive size={22} />} title={courses.length ? 'No matching courses' : 'No courses available'} description={courses.length ? 'Try a broader search.' : 'Create a course first to manage course-specific data.'} action={<button className="pf-admin-button" onClick={() => setEditing(null)}><Plus size={16} /> New course</button>} /> : null}</section>
    <AnimatePresence>{editing !== undefined ? <AdminDialog open onClose={() => setEditing(undefined)} title={editing ? 'Edit course' : 'New course'} description={editing ? 'Update course information without changing its stable relationships.' : 'Create a course for new course-specific workspaces.'}><CourseEditor course={editing} onClose={() => setEditing(undefined)} /></AdminDialog> : null}{deleting ? <AdminDialog open onClose={() => setDeleting(null)} title="Delete course?" description="Only archived courses can be deleted. Existing records are never cascade-deleted." footer={<><button className="pf-admin-button pf-admin-button--quiet" onClick={() => setDeleting(null)}>Cancel</button><button className="pf-admin-button pf-admin-button--danger" onClick={() => void onDeleted()}>Delete course</button></>}><p>Delete <strong>{deleting.name}</strong>? Its related students, orders, content, packages, and questions will remain available in their historical records.</p></AdminDialog> : null}</AnimatePresence><AdminToast toast={toast} onDismiss={() => setToast(null)} />
  </motion.div>;
}
